version: "3.5"
services:
  qgis:
    container_name: tiler
    build:
      context: .
    volumes:
      - ./src:/opt/src
      - projekter:/opt/projekter:rw
      - ./keys:/opt/keys:rw
      - ./conf.ini:/opt/conf.ini
    extra_hosts:
      - "srwebgisadm01:172.16.2.232"
    restart: unless-stopped
  ftp:
    container_name: tiler-ftp
    image: atmoz/sftp:latest
    volumes:
      - projekter:/home/gis/projekter:rw
      - ./pub_keys:/home/gis/.ssh/keys:ro
      - ./host_keys/ssh_host_ed25519_key:/etc/ssh/ssh_host_ed25519_key:ro
      - ./host_keys/ssh_host_rsa_key:/etc/ssh/ssh_host_rsa_key:ro
      - ./fixownership.sh:/etc/sftp.d/fixownership.sh
    ports:
      - "2222:22"
    command: gis::::tiles
    depends_on: [qgis]
    restart: unless-stopped

volumes:
  projekter:
