version: "3.5"
services:
  qgis:
    build:
      context: .
    volumes:
      - ./src:/opt/src
      - ./projekter:/opt/projekter:rw
      - ./conf.ini:/opt/conf.ini
    extra_hosts:
      - "srwebgisadm01:172.16.2.232"
